# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 10

  - name: Experience
    url: experience/
    weight: 20
    
  - name: Posts
    url: blog/
    weight: 30
    
#  - name: Technology Philosophy
#    identifier: technology-philosophy
#    weight: 100
    
#  - name: My Vision for Technology in Education
#    url: technology-philosophy/my-vision-for-technology-in-education
#    parent: technology-philosophy
#    weight: 100

#  - name: Technology Tutorial
#    url: technology-philosophy/tutorial/
#    parent: technology-philosophy
#   weight: 200
    
#  - name: Lesson Plan Assignments
#    url: technology-philosophy/assignments
#    parent: technology-philosophy
#    weight: 300

  - name: Projects  
    url: projects/
    weight: 40

  - name: "Parents: Start Here"
    url: parents-start-here/
    weight: 50